spring:
    profiles:
        default: random, jpa
    datasource:
        url: jdbc:h2:mem:url-storage
        driver-class-name: org.h2.Driver
        username: yho
        password: localusage
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
