
spring:
    application:
        name: Url Store
    datasource:
        url: jdbc:h2:mem:url-storage
        driver-class-name: org.h2.Driver
        username: yho
        password: localusage
    h2:
        console:
            enabled: true
            path: /h2-console

server:
    port: 8081